# Generated by Django 3.2.18 on 2023-04-22 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id_alumno', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=75, null=True)),
                ('apellido', models.CharField(blank=True, max_length=75, null=True)),
                ('tipo_doc', models.CharField(max_length=5)),
                ('nro_doc', models.CharField(max_length=15)),
                ('foto', models.TextField(blank=True, null=True)),
                ('fec_nacimiento', models.CharField(max_length=10)),
                ('tipo_tel', models.CharField(max_length=5)),
                ('nro_tel', models.CharField(max_length=75)),
                ('correo', models.CharField(max_length=100)),
                ('fec_inicio', models.CharField(max_length=10)),
                ('activo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alumno',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AlumnoClase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faltas', models.IntegerField()),
                ('calificacion', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'alumno_clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Clase',
            fields=[
                ('id_clase', models.AutoField(primary_key=True, serialize=False)),
                ('clase', models.CharField(blank=True, max_length=35, null=True)),
                ('periodo', models.IntegerField(blank=True, null=True)),
                ('capacidad', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'clase',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id_materia', models.AutoField(primary_key=True, serialize=False)),
                ('materia', models.CharField(blank=True, max_length=35, null=True)),
                ('carrera', models.CharField(blank=True, max_length=35, null=True)),
                ('anio', models.CharField(blank=True, max_length=15, null=True)),
                ('cuatrimestre', models.CharField(blank=True, max_length=15, null=True)),
            ],
            options={
                'db_table': 'materia',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id_pais', models.AutoField(primary_key=True, serialize=False)),
                ('iso2', models.CharField(blank=True, max_length=2, null=True)),
                ('iso3', models.CharField(blank=True, max_length=3, null=True)),
                ('isonum', models.IntegerField()),
                ('pais', models.CharField(blank=True, max_length=75, null=True)),
                ('bandera', models.TextField(blank=True, null=True)),
                ('numorden', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'pais',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id_profesor', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=75, null=True)),
                ('apellido', models.CharField(blank=True, max_length=75, null=True)),
                ('tipo_doc', models.CharField(max_length=5)),
                ('nro_doc', models.CharField(max_length=15)),
                ('foto', models.TextField(blank=True, null=True)),
                ('fec_nacimiento', models.CharField(max_length=10)),
                ('tipo_tel', models.CharField(max_length=5)),
                ('nro_tel', models.CharField(max_length=75)),
                ('correo', models.CharField(max_length=100)),
                ('fec_inicio', models.CharField(max_length=10)),
                ('activo', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'profesor',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id_provincia', models.AutoField(primary_key=True, serialize=False)),
                ('provincia', models.CharField(blank=True, max_length=35, null=True)),
            ],
            options={
                'db_table': 'provincia',
                'managed': False,
            },
        ),
    ]
